export const baseFields = (table) => {
  table.increments('id');
  table.string('leadId', 255);
  table.string('agentId', 255);
  table.string('account_id', 255);
  table.string('officeId', 255);
  table.string('accountTypeId', 255);
  table.string('conversionStatusId', 255);
  table.string('retentionStatusId', 255);
  table.string('virtualGroupID', 255);
  table.string('clickId', 255);
  table.string('campaignId', 255);
  table.string('affiliateId', 255);
  table.string('termsAcceptanceStatusId', 255);
  table.integer('status_id', 4);
  table.string('old_affiliate_id', 255);
  table.boolean('isSuspended');
  table.boolean('isVerified');
  table.boolean('isTest');
  table.string('firstName', 255);
  table.string('lastName', 255);
  table.string('email', 255);
  table.string('phone', 255);
  table.string('phone2', 255);
  table.string('cellphone', 255);
  table.string('departmentName', 255);
  table.string('conversionStatusTitle', 255);
  table.string('retentionStatusTitle', 255);
  table.string('conversionCategoryTitle', 255);
  table.string('retentionCategoryTitle', 255);
  table.string('agentName', 255);
  table.string('officeName', 255);
  table.string('languageCode', 255);
  table.string('countryType', 255);
  table.string('countryCode', 255);
  table.string('town', 255);
  table.string('postalCode', 255);
  table.string('address', 255);
  table.string('address2', 255);
  table.date('birthday');
  table.string('marker', 255);
  table.string('currencyCode', 255);
  table.string('ip', 255);
  table.string('tracking', 255);
  table.string('subtracking', 255);
  table.string('param', 255);
  table.boolean('hasDeposited');
  table.string('balance', 255);
  table.string('balanceUsd', 255);
  table.string('totalDepositAmount', 255);
  table.string('totalDepositAmountUsd', 255);
  table.string('country_code_by_phone', 255);
  table.string('normalized_phone', 255);
  table.string('promotion_code', 255);
  table.string('security_phrase', 255);
  table.string('campaign_name', 255);
  table.string('import_filename', 255);
  table.boolean('created_in_crm').notNullable().defaultTo(false);
  table.timestamp('lastTransactionTimestamp');
  table.timestamp('verifiedChangedTimestamp');
  table.timestamp('registrationTimestamp');
  table.timestamp('lastLoginTimestamp');
  table.timestamp('lastActiveTimestamp');
  table.timestamp('lastOnlineTimestamp');
  table.timestamp('lastUpdateTimestamp');
  table.timestamp('lastTradeTimestamp');
  table.timestamp('firstDepositTimestamp');
  table.timestamp('lastDepositTimestamp');
  table.timestamp('created_at');
  table.timestamp('updated_at');
};
